{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bibtex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bibtex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bibtex/bibtex_{{ version }}.tar.gz
  sha256: ec81b4ee5b43f2114afd18d266f4633451abe20013422eb03848f00924b79167

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-stringr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-stringr

test:
  commands:
    - $R -e "library('bibtex')"           # [not win]
    - "\"%R%\" -e \"library('bibtex')\""  # [win]

about:
  home: https://github.com/romainfrancois/bibtex
  license: GPL-2.0-or-later
  summary: Utility to parse a bibtex file.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - tfenne

# Package: bibtex
# Version: 0.4.2.1
# Title: Bibtex Parser
# Authors@R: c( person("Romain", "Francois", role = c("aut", "cre"), email = "romain@r-enthusiasts.com"), person("Kurt", "Hornik", role = "ctb", email = "Kurt.Hornik@R-project.org"), person("Michael", "Koohafkan", role = "ctb", email = "michael.koohafkan@gmail.com"), person(c("Mathew", "W."), "McLean", role = "ctb", email = "mathew.w.mclean@gmail.com" ) )
# Description: Utility to parse a bibtex file.
# Depends: R (>= 3.0.2)
# Imports: stringr, utils
# Suggests: testthat
# License: GPL (>= 2)
# LazyLoad: yes
# BugReports: https://github.com/romainfrancois/bibtex/issues
# URL: https://github.com/romainfrancois/bibtex
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: yes
# Packaged: 2019-12-20 20:36:03 UTC; ripley
# Author: Romain Francois [aut, cre], Kurt Hornik [ctb], Michael Koohafkan [ctb], Mathew W. McLean [ctb]
# Maintainer: Romain Francois <romain@r-enthusiasts.com>
# Repository: CRAN
# Date/Publication: 2019-12-20 22:04:43 UTC
