{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bibtex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bibtex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bibtex/bibtex_{{ version }}.tar.gz
  sha256: f3c1a0a4e666c4addd73ff13ce8ce073d73d10ebca36d333328ade8a0b493ed1

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-backports >=1.4.0
  run:
    - r-base
    - r-backports >=1.4.0

test:
  commands:
    - $R -e "library('bibtex')"           # [not win]
    - "\"%R%\" -e \"library('bibtex')\""  # [win]

about:
  home: https://github.com/romainfrancois/bibtex
  license: GPL-2.0-or-later
  summary: Utility to parse a bibtex file.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - tfenne

# Package: bibtex
# Version: 0.4.2.1
# Title: Bibtex Parser
# Authors@R: c( person("Romain", "Francois", role = c("aut", "cre"), email = "romain@r-enthusiasts.com"), person("Kurt", "Hornik", role = "ctb", email = "Kurt.Hornik@R-project.org"), person("Michael", "Koohafkan", role = "ctb", email = "michael.koohafkan@gmail.com"), person(c("Mathew", "W."), "McLean", role = "ctb", email = "mathew.w.mclean@gmail.com" ) )
# Description: Utility to parse a bibtex file.
# Depends: R (>= 3.0.2)
# Imports: stringr, utils
# Suggests: testthat
# License: GPL (>= 2)
# LazyLoad: yes
# BugReports: https://github.com/romainfrancois/bibtex/issues
# URL: https://github.com/romainfrancois/bibtex
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: yes
# Packaged: 2019-12-20 20:36:03 UTC; ripley
# Author: Romain Francois [aut, cre], Kurt Hornik [ctb], Michael Koohafkan [ctb], Mathew W. McLean [ctb]
# Maintainer: Romain Francois <romain@r-enthusiasts.com>
# Repository: CRAN
# Date/Publication: 2019-12-20 22:04:43 UTC
