appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: UsjRJLWbX56hGwsEuDAShDzELR8YRoLz+wLOVxrjLRj4KaK38xgvPDIXQCYtWKeYK7ptgdj6Y1a5jhDxdRrtAinyifOXajG2Kpb/hWFzDzcE9Cg0A+clZG455B8hflGaTwVTrKQ3Xzc98MQbDwxbGPBi6hlwLQdbCNeI88l8FFcLSl36iuDi9NJnyfZ7mcNbqjsvYwB8O1Z2FmRFAwNcOr083Mzqy6hz+bOKbSxJWaW5JAcgqOcXtc3+koPPM9F1suG8weh1Qd7nPKYGC0wdpLszlCEm7QiA3iR86uzLfh2VNhtnQaGqRkElVheD9+Lg2BBK5OVnkxS/7eRKA9gXv/yDRcxaP2Uk2WRpyP2oM+tCPx2a20E1tG5XPwu/Km06cUxgPVV0Lj9iYRxA8AJ8PIVW1fkZX4vwfXJPR81QYpwt+x2ZGuaU/qncpQxveqw+j9Mm3tAttFT10eOZG2N6QgFIFCm0jFbUwxqmIXS4Q8zOfgP298srdZdePX/yQYFSTyWVqSr0o+1Q1+TV4InM8JVvgN7VR4eWSYIFooIkB6i9wBOGdyVV7j5Qdz3LG+jDbB3haxRTVC0U7f2gwfNXCf1VfP2cJ0iUinKb+dFs4Sg4PEhoT9vZ2rt360ojXKh7JObR6fzpSne9t3tx77e6XiKFiLcnVhi+i+NaO6Oy/lw=}
